enhancement:
  - '/(feat|request|new|improve|create|build)/i'
bug:
  - '/(bug|fix|issue|solve|correct)/i'
configuration:
  - '/(config)/i'
documentation:
  - '/(docs|document|readme)/i'
duplicate:
  - '/(duplicate)/i'
github_actions:
  - '/(github_actions|github)/'
github:
  - '/(github)/i'
help wanted:
  - '/(help|need|info)/i'
invalid:
  - '/(invalid)/i'
question:
  - '/(query|\?|question|ask)/i'
wontfix:
  - '/(nofix|nosolution)/i'
critical:
  - '/(critical|urgent)/i'
