name: 'Autolock Issues'

on:
  schedule:
    - cron: '0 12 * * FRI'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '7'
          exclude-issue-created-before: ''
          exclude-issue-created-after: ''
          exclude-issue-created-between: ''
          exclude-issue-closed-before: ''
          exclude-issue-closed-after: ''
          exclude-issue-closed-between: ''
          include-any-issue-labels: ''
          include-all-issue-labels: ''
          exclude-any-issue-labels: ''
          add-issue-labels: 'outdated issue'
          remove-issue-labels: ''
          issue-comment: 'This issue has been automatically locked since there has not been any recent activity in past 7 days after it was closed. Please open a new issue for related bugs.'
          issue-lock-reason: 'resolved'
          process-only: 'issues'
          log-output: true
