name: 'Autolock Pull Request'

on:
  schedule:
    - cron: '0 12 1/15 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ github.token }}
          pr-inactive-days: '15'
          exclude-pr-created-before: ''
          exclude-pr-created-after: ''
          exclude-pr-created-between: ''
          exclude-pr-closed-before: ''
          exclude-pr-closed-after: ''
          exclude-pr-closed-between: ''
          include-any-pr-labels: 'automerge'
          include-all-pr-labels: ''
          exclude-any-pr-labels: ''
          add-pr-labels: 'outdated pull request'
          remove-pr-labels: ''
          pr-comment: 'This pull request has been automatically locked since there has not been any activity in the past 15 days after it was closed.'
          pr-lock-reason: 'resolved'
          log-output: true
