name: 'Close Stale Issues and Pull Requests'
on:
  schedule:
    - cron: '0 12 * * SUN'
  pull_request:
    paths:
      - .github/workflows/close_stale_issues_and_prs.yml
    types:
      - opened
      - synchronize

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          ascending: true
          close-issue-message: 'Autoclose: Stale issue'
          close-pr-message: 'Autoclose: Stale pull request'
          days-before-issue-stale: 120
          days-before-pr-stale: 30
          days-before-close: 7
          debug-only: ${{ github.event_name == 'pull_request' }}
          exempt-all-milestones: true
          exempt-issue-labels: blocked,do-not-close,feature,security
          exempt-pr-labels: blocked,do-not-close,feature,security
          operations-per-run: ${{ github.event_name == 'pull_request' && 1000 || 900}}
          stale-issue-label: stale
          stale-issue-message: 'Autostale: This issue is marked as stale'
          stale-pr-label: stale
          stale-pr-message: 'Autostale: This pull request is marked as stale'
